### ISSUE TITLE
やりたいことリスト

### ISSUE THREAD

**Issue by kameiatsushi** [kameiatsushi/AtsushiKamei#141]

**Comment by kameiatsushi** [comment]
# やりたいこと
## インターネットの勉強
## 大学数学の勉強
## 量子力学の勉強
## プログラミングの勉強
## 教育に関する勉強
## 小説を読む
## 小説を書く
## バスケ
## youtube見る
## 漫画
## 旅行

**Comment by kameiatsushi** [comment]
# 仕事関連
## to do listの作成
## 各教科の勉強法の確立
## 文賢
## 新谷スクールの授業
## youtube投稿
## ウェブサイトを綺麗にする
## 営業
## バイトの募集
## noteやブログなど
# その他雑務
### 住民票移す
### 実家を出る

**Comment by kameiatsushi** [comment]
# その他
# 小説を読む
# 小説を書く
# バスケ
# youtube見る
# 漫画
# 旅行
# マイクラ

**Comment by lifelabkyoto** [comment]
aa
